language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libnotmuch-dev

script:
  - cargo build --no-default-features --verbose --all
  - cargo test --no-default-features --verbose --all
