[package]
name = "notmuch"
version = "0.0.6"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]

homepage = "https://github.com/vhdirk/notmuch-rs"
repository = "https://github.com/vhdirk/notmuch-rs"
description = "Rust interface and bindings for notmuch"
license = "GPL-3.0+"

[dependencies]
libc = "0.2"
